"""Unit tests for main FastAPI application configuration.

Tests for Swagger UI OAuth2/OIDC integration and outbox handler registration.
Following TDD approach - tests written before implementation.
"""

from __future__ import annotations

from unittest.mock import AsyncMock, MagicMock, patch

import pytest
from fastapi import FastAPI
from pydantic import SecretStr


TEST_ISSUER = "https://auth.example.com/realms/test"
TEST_CLIENT_ID = "test-api-client"
TEST_CLIENT_SECRET = "test-secret"
TEST_SWAGGER_CLIENT_ID = "test-swagger-client"


@pytest.fixture
def mock_oidc_settings() -> MagicMock:
    """Create mock OIDC settings for testing."""
    settings = MagicMock()
    settings.issuer_url = TEST_ISSUER
    settings.client_id = TEST_CLIENT_ID
    settings.client_secret = SecretStr(TEST_CLIENT_SECRET)
    settings.swagger_client_id = TEST_SWAGGER_CLIENT_ID
    return settings


@pytest.fixture
def test_app() -> FastAPI:
    """Create a minimal test FastAPI app."""
    return FastAPI(
        title="Test API",
        version="1.0.0",
        description="Test application",
    )


class TestConfigureSwaggerOAuth2:
    """Tests for configure_swagger_oauth2 function.

    Note: The OAuth2 security scheme is now auto-generated by FastAPI's
    OAuth2AuthorizationCodeBearer when routes depend on it. These tests
    only verify the swagger_ui_init_oauth configuration.
    """

    def test_swagger_ui_init_oauth_configured_when_oidc_valid(
        self,
        test_app: FastAPI,
        mock_oidc_settings: MagicMock,
    ) -> None:
        """Swagger UI init oauth should be configured when OIDC settings are valid."""
        from main import configure_swagger_oauth2

        with patch("main.get_oidc_settings", return_value=mock_oidc_settings):
            configure_swagger_oauth2(test_app)

        assert test_app.swagger_ui_init_oauth is not None
        assert test_app.swagger_ui_init_oauth["clientId"] == TEST_SWAGGER_CLIENT_ID

    def test_pkce_enabled_in_swagger_config(
        self,
        test_app: FastAPI,
        mock_oidc_settings: MagicMock,
    ) -> None:
        """usePkceWithAuthorizationCodeGrant should be True."""
        from main import configure_swagger_oauth2

        with patch("main.get_oidc_settings", return_value=mock_oidc_settings):
            configure_swagger_oauth2(test_app)

        assert test_app.swagger_ui_init_oauth is not None
        assert (
            test_app.swagger_ui_init_oauth["usePkceWithAuthorizationCodeGrant"] is True
        )

    def test_swagger_not_configured_when_oidc_settings_fail(
        self,
        test_app: FastAPI,
    ) -> None:
        """Swagger OAuth2 should not be configured when OIDC settings fail."""
        from main import configure_swagger_oauth2

        with patch(
            "main.get_oidc_settings",
            side_effect=Exception("Missing client_secret"),
        ):
            configure_swagger_oauth2(test_app)

        # swagger_ui_init_oauth should remain None (not set)
        assert test_app.swagger_ui_init_oauth is None

    def test_scopes_configured_in_swagger_init(
        self,
        test_app: FastAPI,
        mock_oidc_settings: MagicMock,
    ) -> None:
        """Scopes should be configured in swagger_ui_init_oauth."""
        from main import configure_swagger_oauth2

        with patch("main.get_oidc_settings", return_value=mock_oidc_settings):
            configure_swagger_oauth2(test_app)

        assert test_app.swagger_ui_init_oauth is not None
        assert "scopes" in test_app.swagger_ui_init_oauth
        assert "openid" in test_app.swagger_ui_init_oauth["scopes"]

    def test_uses_public_swagger_client_not_api_client(
        self,
        test_app: FastAPI,
        mock_oidc_settings: MagicMock,
    ) -> None:
        """Should use the public swagger_client_id, not the confidential API client."""
        from main import configure_swagger_oauth2

        with patch("main.get_oidc_settings", return_value=mock_oidc_settings):
            configure_swagger_oauth2(test_app)

        assert test_app.swagger_ui_init_oauth is not None
        # Should use swagger_client_id, not client_id
        assert test_app.swagger_ui_init_oauth["clientId"] == TEST_SWAGGER_CLIENT_ID
        assert test_app.swagger_ui_init_oauth["clientId"] != TEST_CLIENT_ID


class TestOutboxHandlerRegistration:
    """Regression tests for outbox handler wiring in main.py lifespan.

    These tests guard against the class of bug where a bounded context
    translator is implemented but never registered with the composite handler,
    causing outbox events to silently fail with 'No handler registered'.
    """

    def _build_composite_handler(self):  # type: ignore[return]
        """Reproduce the handler registration logic from kartograph_lifespan."""
        from iam.infrastructure.outbox import IAMEventTranslator
        from infrastructure.outbox.composite import CompositeEventHandler
        from infrastructure.outbox.spicedb_handler import SpiceDBEventHandler
        from management.infrastructure.outbox.translator import (
            ManagementEventTranslator,
        )

        authz = MagicMock()
        authz.write_relationship = AsyncMock()
        authz.delete_relationship = AsyncMock()
        authz.delete_relationships_by_filter = AsyncMock()

        handler = CompositeEventHandler()
        handler.register(
            SpiceDBEventHandler(translator=IAMEventTranslator(), authz=authz),
            handler_name="iam",
        )
        handler.register(
            SpiceDBEventHandler(translator=ManagementEventTranslator(), authz=authz),
            handler_name="management",
        )
        return handler

    def test_data_source_created_is_handled(self) -> None:
        """DataSourceCreated must have a registered handler (regression: TASK-101)."""
        handler = self._build_composite_handler()
        assert "DataSourceCreated" in handler.supported_event_types()

    def test_data_source_deleted_is_handled(self) -> None:
        handler = self._build_composite_handler()
        assert "DataSourceDeleted" in handler.supported_event_types()

    def test_data_source_updated_is_handled(self) -> None:
        handler = self._build_composite_handler()
        assert "DataSourceUpdated" in handler.supported_event_types()

    def test_data_source_sync_requested_is_handled(self) -> None:
        handler = self._build_composite_handler()
        assert "DataSourceSyncRequested" in handler.supported_event_types()

    def test_knowledge_graph_created_is_handled(self) -> None:
        handler = self._build_composite_handler()
        assert "KnowledgeGraphCreated" in handler.supported_event_types()

    def test_knowledge_graph_deleted_is_handled(self) -> None:
        handler = self._build_composite_handler()
        assert "KnowledgeGraphDeleted" in handler.supported_event_types()

    def test_all_iam_events_are_handled(self) -> None:
        """All IAM domain events must be covered by the composite handler."""
        from iam.infrastructure.outbox import IAMEventTranslator

        iam_events = IAMEventTranslator().supported_event_types()
        handler = self._build_composite_handler()
        missing = iam_events - handler.supported_event_types()
        assert not missing, (
            f"IAM events missing from composite handler: {sorted(missing)}"
        )

    def test_all_management_events_are_handled(self) -> None:
        """All Management domain events must be covered by the composite handler."""
        from management.infrastructure.outbox.translator import (
            ManagementEventTranslator,
        )

        mgmt_events = ManagementEventTranslator().supported_event_types()
        handler = self._build_composite_handler()
        missing = mgmt_events - handler.supported_event_types()
        assert not missing, (
            f"Management events missing from composite handler: {sorted(missing)}"
        )
