#!/usr/bin/env bash
# worktree-dev.sh — Start a dev stack for a git worktree without port conflicts.
#
# Usage:
#   scripts/worktree-dev.sh [WORKTREE_ID]
#
# WORKTREE_ID is an integer (0-9). Each ID uses a unique port range so multiple
# worktrees can run make dev simultaneously on the same machine.
#
# Port allocation (base + WORKTREE_ID * 100):
#   ID=0 (default): 8080, 9000, 50051, 5432, 8000, 3000
#   ID=1:           8180, 9100, 50151, 5532, 8100, 3100
#   ID=2:           8280, 9200, 50251, 5632, 8200, 3200
#
# The script writes a .env.worktree file in the repo root and then calls make dev.
# Remove .env.worktree to reset to defaults.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

WORKTREE_ID="${1:-0}"

if ! [[ "$WORKTREE_ID" =~ ^[0-9]+$ ]]; then
  echo "ERROR: WORKTREE_ID must be a non-negative integer, got: $WORKTREE_ID" >&2
  exit 1
fi

PORT_OFFSET=$(( WORKTREE_ID * 100 ))

KEYCLOAK_PORT=$(( 8080 + PORT_OFFSET ))
KEYCLOAK_HEALTH_PORT=$(( 9000 + PORT_OFFSET ))
SPICEDB_PORT=$(( 50051 + PORT_OFFSET ))
POSTGRES_PORT=$(( 5432 + PORT_OFFSET ))
API_PORT=$(( 8000 + PORT_OFFSET ))
DEV_UI_PORT=$(( 3000 + PORT_OFFSET ))
DEV_UI_HMR_PORT=$(( 24678 + PORT_OFFSET ))
COMPOSE_PROJECT_NAME="kartograph-wt${WORKTREE_ID}"

cat > "${REPO_ROOT}/.env.worktree" <<EOF
# Auto-generated by scripts/worktree-dev.sh — do not edit manually.
# Re-run the script to regenerate.
WORKTREE_ID=${WORKTREE_ID}
COMPOSE_PROJECT_NAME=${COMPOSE_PROJECT_NAME}
KEYCLOAK_PORT=${KEYCLOAK_PORT}
KEYCLOAK_HEALTH_PORT=${KEYCLOAK_HEALTH_PORT}
SPICEDB_PORT=${SPICEDB_PORT}
POSTGRES_PORT=${POSTGRES_PORT}
API_PORT=${API_PORT}
DEV_UI_PORT=${DEV_UI_PORT}
DEV_UI_HMR_PORT=${DEV_UI_HMR_PORT}
EOF

echo "Worktree dev environment configured (WORKTREE_ID=${WORKTREE_ID}):"
echo "  Compose project : ${COMPOSE_PROJECT_NAME}"
echo "  Keycloak        : http://localhost:${KEYCLOAK_PORT}"
echo "  SpiceDB gRPC    : localhost:${SPICEDB_PORT}"
echo "  Postgres        : localhost:${POSTGRES_PORT}"
echo "  API             : http://localhost:${API_PORT}"
echo "  Dev UI          : http://localhost:${DEV_UI_PORT}"
echo ""
echo "Starting dev stack..."
make -C "${REPO_ROOT}" dev WORKTREE_ID="${WORKTREE_ID}"
